server:
  port: 8080

spring:
  datasource:
    #driver-class-name: com.mysql.cj.jdbc.Driver
    #url: jdbc:mysql://localhost:3306/mybatis-plus-high?useSSL=false&serverTimezone=GMT%2B8

    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
    url: jdbc:p6spy:mysql://localhost:3306/mybatis-plus-high?useSSL=false&serverTimezone=GMT%2B8

    username: root
    password: mysql94

logging:
  level:
    com:
      ethan:
        dao: trace
  pattern:
    console: '%p%m%n'

# mp默认逻辑删除配置就是下面的
# 如果项目中逻辑删除字段值与默认的一致，可以省略该配置
mybatis-plus:
  # 全局配置
  global-config:
    db-config:
      # 逻辑未删除将删除标志字段deleted置为0
      logic-not-delete-value: 0
      # 逻辑已删除将删除标志字段deleted置为1
      logic-delete-value: 1

